services:
  - type: web
    name: portfolio-django
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn portfolio_site.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_site.settings
      - key: SECRET_KEY
        generateValue: true
